(()=>{
const $=id=>document.getElementById(id);
const K={settings:'majlis.settings',history:'majlis.history',draft:'majlis.draft'};
let state={mode:'cours',content:'',topic:'',busy:false,controller:null,debate:[],settings:{apiKey:'',model:'gemini-2.5-flash',profile:''}};
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
const md=s=>window.marked?marked.parse(s||''):String(s||'').replace(/\n/g,'<br>');
function apiBadge(ok,text){const e=$('apiState');if(!e)return;e.textContent=text;e.className='badge '+(ok?'ok':'bad')}
function setStatus(text=''){$('status').textContent=text}
function setBusy(v,msg=''){state.busy=v;$('launch').disabled=v;$('stop').hidden=!v;if(msg!==undefined)setStatus(msg)}
function currentMode(){return MAJLIS_MODES.find(m=>m.id===state.mode)||MAJLIS_MODES[0]}
function renderModes(){const r=$('modes');r.innerHTML='';MAJLIS_MODES.forEach(m=>{const b=document.createElement('button');b.className='mode '+(m.id===state.mode?'active':'');b.textContent=m.label;b.type='button';b.onclick=()=>selectMode(m.id);r.appendChild(b)});$('modeDesc').textContent=currentMode().desc}
function selectMode(id){state.mode=id;renderModes();const d=id==='debat';$('normalPanel').hidden=d;$('debatePanel').hidden=!d}
function systemPrompt(extra=''){return MAJLIS_SYSTEM+(state.settings.profile?`\n\nProfil de l'étudiant: ${state.settings.profile}`:'')+extra}
async function gemini(system,messages,maxTokens=3500){const key=state.settings.apiKey;if(!key){openSettings();throw new Error('Ajoute ta clé Gemini dans Réglages.')}const model=state.settings.model||'gemini-2.5-flash';const contents=messages.map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:m.content}]}));const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents,generationConfig:{temperature:.65,topP:.92,maxOutputTokens:maxTokens}}),signal:state.controller?.signal});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error?.message||`Gemini ${res.status}`);const text=(data.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('\n').trim();if(!text)throw new Error('Gemini n’a renvoyé aucun texte.');return text}
function renderFolio(){if(!state.content){$('folio').innerHTML='<div class="empty"><div><b>Ton académie personnelle</b><span>Choisis un mode, écris un sujet et lance l’étude.</span></div></div>';$('folioActions').hidden=true;return}$('folio').innerHTML=md(state.content);$('folioActions').hidden=false}
async function runMode(){const m=currentMode();if(m.id==='debat')return;const t=$('topic').value.trim();if(!t){setStatus('Écris d’abord un sujet.');return}state.topic=t;state.controller=new AbortController();setBusy(true,'Majlis réfléchit…');try{const p=m.prompt(t,$('angle').value.trim(),$('level').value,$('depth').value);state.content=await gemini(systemPrompt(),[{role:'user',content:p}],4200);renderFolio();saveDraft();autoSave();setStatus('Cours prêt.')}catch(e){setStatus(e.name==='AbortError'?'Génération arrêtée.':`Erreur : ${e.message}`)}finally{state.controller=null;setBusy(false,$('status').textContent)}}
async function follow(kind){if(!state.content){setStatus('Lance d’abord un cours.');return}const map={deeper:'Approfondis ce cours d’un niveau supplémentaire. Ne répète pas. Identifie les hypothèses cachées, les débats de recherche, les objections fortes et les limites empiriques.',challenge:'Attaque intellectuellement le contenu précédent. Liste les simplifications, contre-exemples, causalités fragiles, données manquantes et l’argument opposé le plus sérieux.',quiz:'À partir du contenu précédent, crée un test sans réponses: 5 compréhension, 4 raisonnement, 1 cas, 1 dissertation, 1 piège.'};state.controller=new AbortController();setBusy(true,'Analyse en cours…');try{const r=await gemini(systemPrompt(),[{role:'user',content:`Sujet: ${state.topic}\n\nContenu étudié:\n${state.content}\n\nInstruction: ${map[kind]}`}],3000);state.content+=`\n\n---\n\n${r}`;renderFolio();saveDraft();setStatus('Analyse ajoutée.')}catch(e){setStatus(`Erreur : ${e.message}`)}finally{state.controller=null;setBusy(false,$('status').textContent)}}
function hist(){return load(K.history,[])}
function saveSession(notify=true){if(!state.content)return;const h=hist();h.unshift({id:Date.now(),topic:state.topic,mode:state.mode,content:state.content,date:new Date().toISOString()});save(K.history,h.slice(0,40));renderHistory();if(notify)setStatus('Session enregistrée.')}
function autoSave(){saveSession(false)}
function saveDraft(){save(K.draft,{topic:$('topic').value,angle:$('angle').value,level:$('level').value,depth:$('depth').value,mode:state.mode,content:state.content})}
function restoreDraft(){const d=load(K.draft,null);if(!d)return;$('topic').value=d.topic||'';$('angle').value=d.angle||'';$('level').value=d.level||'M1';$('depth').value=d.depth||'Avancé';state.mode=d.mode||'cours';state.content=d.content||'';state.topic=d.topic||'';selectMode(state.mode);renderFolio()}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderHistory(){const r=$('history'),h=hist();r.innerHTML='';if(!h.length){r.innerHTML='<span class="muted">Aucune session enregistrée.</span>';return}h.slice(0,12).forEach(x=>{const d=document.createElement('div');d.className='hist';d.innerHTML=`<b>${escapeHtml(x.topic||'Sans titre')}</b><small>${escapeHtml(x.mode)} · ${new Date(x.date).toLocaleDateString('fr-FR')}</small>`;d.onclick=()=>{state.topic=x.topic;state.content=x.content;state.mode=x.mode==='debat'?'cours':x.mode;$('topic').value=x.topic;selectMode(state.mode);renderFolio();window.scrollTo({top:0,behavior:'smooth'})};r.appendChild(d)})}
function showSettingsResult(text='',ok=null){const e=$('settingsResult');if(!e)return;e.textContent=text;e.className='settings-result '+(ok===true?'ok':ok===false?'bad':'')}
function getFormSettings(){return{apiKey:$('apiKey').value.trim(),model:$('model').value||'gemini-2.5-flash',profile:$('profile').value.trim()}}
function openSettings(){state.settings=Object.assign({apiKey:'',model:'gemini-2.5-flash',profile:''},load(K.settings,{}));$('apiKey').value=state.settings.apiKey||'';$('model').value=state.settings.model||'gemini-2.5-flash';$('profile').value=state.settings.profile||'';showSettingsResult(state.settings.apiKey?'Clé enregistrée sur cet iPhone.':'Colle ta clé Gemini puis appuie sur « Tester Gemini ».');$('settings').hidden=false;document.body.style.overflow='hidden';setTimeout(()=>$('apiKey').focus(),50)}
function closeSettings(){$('settings').hidden=true;document.body.style.overflow='';document.activeElement?.blur()}
function saveSettings(){const next=getFormSettings();if(!next.apiKey){showSettingsResult('Colle d’abord ta clé Gemini.',false);return}state.settings=next;save(K.settings,next);apiBadge(true,'Gemini configuré');closeSettings();setStatus('Réglages enregistrés. Tu peux utiliser Majlis.')}
async function testApi(){const next=getFormSettings();if(!next.apiKey){showSettingsResult('Colle d’abord ta clé Gemini.',false);return}const btn=$('testApi');btn.disabled=true;btn.textContent='Test…';showSettingsResult('Connexion à Gemini…');try{const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(next.model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':next.apiKey},body:JSON.stringify({contents:[{role:'user',parts:[{text:'Réponds seulement: OK'}]}],generationConfig:{maxOutputTokens:8,temperature:0}})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error?.message||`Erreur ${res.status}`);state.settings=next;save(K.settings,next);apiBadge(true,'Gemini connecté');showSettingsResult('Gemini connecté ✓',true);setStatus('Gemini connecté. Majlis est prêt.');setTimeout(closeSettings,350)}catch(e){apiBadge(false,'Gemini à vérifier');showSettingsResult(`Connexion refusée : ${e.message||'vérifie la clé'}`,false)}finally{btn.disabled=false;btn.textContent='Tester Gemini'}}
async function startDebate(){const t=$('debateTopic').value.trim();if(!t){setStatus('Écris une affirmation à débattre.');return}state.debate=[];state.topic=t;state.controller=new AbortController();setBusy(true,'Préparation de la contradiction…');try{const r=await gemini(DEBATE_SYSTEM,[{role:'user',content:`Sujet ou affirmation: ${t}. Prends une position ferme et lance par l’objection la plus difficile.`}],900);state.debate=[{role:'assistant',content:r}];renderThread();$('debateReplyRow').hidden=false;$('verdict').hidden=false;setStatus('Débat ouvert.')}catch(e){setStatus(`Erreur : ${e.message}`)}finally{state.controller=null;setBusy(false,$('status').textContent)}}
async function replyDebate(){const v=$('debateReply').value.trim();if(!v)return;state.debate.push({role:'user',content:v});$('debateReply').value='';renderThread();state.controller=new AbortController();setBusy(true,'Réplique…');try{const r=await gemini(DEBATE_SYSTEM,state.debate,1000);state.debate.push({role:'assistant',content:r});renderThread()}catch(e){setStatus(`Erreur : ${e.message}`)}finally{state.controller=null;setBusy(false,$('status').textContent)}}
async function verdict(){if(!state.debate.length)return;const transcript=state.debate.map(m=>`${m.role==='user'?'Étudiant':'Contradicteur'}: ${m.content}`).join('\n');state.controller=new AbortController();setBusy(true,'Évaluation…');try{const r=await gemini(systemPrompt(),[{role:'user',content:`Évalue le raisonnement de l’étudiant dans ce débat:\n${transcript}\n\nDonne: meilleure idée, faiblesse centrale, prémisse insuffisante, meilleur contre-argument, amélioration précise, puis note /20 avec sous-notes définitions, logique, preuves, nuance.`}],1600);state.debate.push({role:'assistant',content:`## Verdict\n\n${r}`});renderThread()}catch(e){setStatus(`Erreur : ${e.message}`)}finally{state.controller=null;setBusy(false,$('status').textContent)}}
function renderThread(){const r=$('thread');r.innerHTML='';state.debate.forEach(m=>{const d=document.createElement('div');d.className='msg '+(m.role==='user'?'me':'them');d.innerHTML=`<span class="who">${m.role==='user'?'Toi':'Majlis'}</span>${md(m.content)}`;r.appendChild(d)});r.scrollTop=r.scrollHeight}
function speak(){if(!state.content||!('speechSynthesis'in window)){setStatus('Lecture vocale indisponible.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance($('folio').innerText);u.lang='fr-FR';u.rate=.98;speechSynthesis.speak(u)}
function initPwa(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
function bind(){$('launch').onclick=runMode;$('stop').onclick=()=>state.controller?.abort();$('deeper').onclick=()=>follow('deeper');$('challenge').onclick=()=>follow('challenge');$('quiz').onclick=()=>follow('quiz');$('save').onclick=()=>saveSession(true);$('copy').onclick=async()=>{if(state.content){try{await navigator.clipboard.writeText(state.content);setStatus('Copié.')}catch{setStatus('Copie impossible sur cet appareil.')}}};$('speak').onclick=speak;$('settingsBtn').onclick=openSettings;$('closeSettings').onclick=closeSettings;$('saveSettings').onclick=saveSettings;$('testApi').onclick=testApi;$('settings').onclick=e=>{if(e.target===$('settings'))closeSettings()};$('apiKey').addEventListener('input',()=>showSettingsResult($('apiKey').value.trim().length>10?'Clé détectée. Tu peux tester ou enregistrer.':'Colle ta clé Gemini.'));$('startDebate').onclick=startDebate;$('sendReply').onclick=replyDebate;$('verdict').onclick=verdict;$('debateReply').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();replyDebate()}};$('topic').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();runMode()}};$('clearHistory').onclick=()=>{if(confirm('Effacer tout l’historique ?')){localStorage.removeItem(K.history);renderHistory()}};['topic','angle','level','depth'].forEach(id=>$(id).addEventListener('change',saveDraft));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('settings').hidden)closeSettings()})}
function init(){state.settings=Object.assign(state.settings,load(K.settings,{}));apiBadge(!!state.settings.apiKey,state.settings.apiKey?'Gemini configuré':'Gemini non configuré');renderModes();bind();restoreDraft();renderHistory();initPwa()}
init();
})();
