(()=>{
'use strict';
const $=id=>document.getElementById(id);
const S='majlis.settings',T='majlis.deepchat.threads',A='majlis.deepchat.active',P='majlis.deepchat.profile';
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modes={
 libre:['◌','Dialogue','Discute avec exigence, nuance et profondeur.'],
 socratique:['?','Socratique','Questionne mes prémisses et force-moi à préciser.'],
 contradiction:['⚔','Contradicteur','Construis le meilleur contre-argument possible.'],
 logique:['△','Audit logique','Repère erreurs, biais, sauts logiques et preuves manquantes.'],
 litteraire:['✦','Littéraire & philo','Analyse forme, images, rythme, symboles et portée philosophique.'],
 carte:['⌘','Carte argumentative','Cartographie thèse, prémisses, preuves, objections et points ouverts.'],
 steelman:['◆','Steelman','Reconstruis la meilleure version de mon idée avant de la tester.']
};
const prompts={
 libre:'Tu es Majlis, partenaire intellectuel exigeant. Reconstruis l’idée avant de la juger, apporte les concepts utiles, distingue ce qui est solide de ce qui est fragile et pousse le raisonnement plus loin. Ne valide pas par politesse.',
 socratique:'Adopte une méthode socratique. Repère la prémisse décisive, le mot ambigu ou le saut logique. Explique pourquoi cela compte puis pose une ou deux questions très précises.',
 contradiction:'Sois le contradicteur le plus sérieux possible. Formule d’abord la version la plus forte de mon idée puis attaque-la : prémisses contestables, mécanismes alternatifs, contre-exemples, coûts cachés, données manquantes, conditions d’échec. Ne caricature jamais.',
 logique:'Fais un audit logique rigoureux : thèse, prémisses explicites et cachées, preuves, inférences, ambiguïtés, causalités supposées, contre-exemples et conclusion. Propose ensuite une version plus solide.',
 litteraire:'Analyse le texte fourni sans inventer mon intention. Distingue observation textuelle et interprétation. Étudie voix, rythme, syntaxe, lexique, images, motifs, répétitions, ruptures, tensions, non-dits, ambiguïtés, architecture et effets. Puis mène une lecture philosophique seulement si le texte l’autorise. Donne plusieurs lectures concurrentes si nécessaire.',
 carte:'Construis une carte argumentative lisible : question centrale → thèse → prémisses → mécanisme → preuves → hypothèses cachées → objections → réponses possibles → points non résolus.',
 steelman:'Reconstruis la version la plus forte, précise et défendable de mon idée, puis soumets cette meilleure version à l’objection la plus difficile.'
};
let mode='libre',busy=false,active=localStorage.getItem(A)||'';
function threads(){return load(T,[])}
function put(arr){save(T,arr.slice(0,30))}
function current(){return threads().find(x=>x.id===active)||null}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function style(){if($('chatStableStyle'))return;const s=document.createElement('style');s.id='chatStableStyle';s.textContent=`
#deepChatPanel{position:relative;z-index:50;background:linear-gradient(145deg,#171d25,#10151c);border-color:#8b6bc744;overflow:visible!important}.cs-head{display:flex;justify-content:space-between;gap:10px}.cs-head h2{font:700 25px Georgia,serif;color:#f4ead7;margin:4px 0}.cs-modes,.cs-quick{display:flex;gap:6px;overflow-x:auto;scrollbar-width:none;padding:10px 0 7px}.cs-modes::-webkit-scrollbar,.cs-quick::-webkit-scrollbar{display:none}.cs-mode,.cs-quick button{flex:0 0 auto;border:1px solid #ffffff14;background:#111820;color:#98a3b2;border-radius:999px;padding:7px 10px;font-size:10px;touch-action:manipulation}.cs-mode.active{border-color:#8b6bc7;color:#efe6ff;background:#8b6bc71b}.cs-chat{min-height:280px;height:min(46vh,500px);overflow:auto;background:#0c1117;border:1px solid #ffffff10;border-radius:12px;padding:10px;display:flex;flex-direction:column;gap:8px}.cs-empty{margin:auto;text-align:center;color:#7e8998;line-height:1.5;font-size:12px}.cs-msg{max-width:94%;padding:10px 11px;border-radius:12px;line-height:1.55;overflow-wrap:anywhere}.cs-msg.user{align-self:flex-end;background:#252e3a;color:#eef1f5}.cs-msg.ai{align-self:flex-start;background:#eee3cf;color:#292117;border-top:3px solid #8b6bc7;font-family:Georgia,serif}.cs-msg p{margin:.25em 0 .75em}.cs-msg p:last-child{margin-bottom:0}.cs-who{display:block;font:800 8px -apple-system,sans-serif;opacity:.55;letter-spacing:.08em;margin-bottom:4px}.cs-compose{position:relative!important;z-index:5000!important;margin-top:7px;padding:8px;border:1px solid #8b6bc780;border-radius:12px;background:#141b24;pointer-events:auto!important}.cs-compose textarea{display:block!important;width:100%!important;min-height:100px!important;max-height:220px!important;padding:12px!important;margin:0!important;background:#0a1016!important;color:#fff!important;border:1px solid #56647a!important;border-radius:9px!important;font-size:16px!important;line-height:1.45!important;opacity:1!important;visibility:visible!important;pointer-events:auto!important;touch-action:auto!important;-webkit-user-select:text!important;user-select:text!important;caret-color:white!important}.cs-compose textarea:focus{outline:2px solid #8b6bc7!important}.cs-foot{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:7px}.cs-status{font-size:10px;color:#8f99a7;min-height:15px;margin-top:5px}.cs-tools{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.cs-thread-select{max-width:260px;font-size:11px}.cs-profile{margin-top:8px;border:1px solid #8b6bc735;border-radius:10px;padding:9px;background:#8b6bc708}.cs-profile[hidden]{display:none!important}.cs-profile textarea{min-height:120px;font-size:12px}body.cs-keyboard .board-bottom-nav{display:none!important}
@media(max-width:720px){#deepChatPanel{min-height:calc(100dvh - 175px);padding:13px!important}.cs-head p{display:none}.cs-head{display:block}.cs-tools{margin-top:7px}.cs-chat{height:40dvh;min-height:230px}.cs-compose{position:sticky!important;bottom:calc(64px + env(safe-area-inset-bottom))!important}.cs-compose textarea{min-height:92px!important}.cs-foot button{min-width:98px;min-height:42px}.cs-foot span{font-size:8px;color:#7f8997}}
`;document.head.appendChild(s)}
function ui(){style();$('deepChatPanel')?.remove();const p=document.createElement('section');p.id='deepChatPanel';p.className='panel deep-chat';p.innerHTML=`<div class="cs-head"><div><div class="label">CHAT INTELLECTUEL</div><h2>Majlis Socratique</h2><p class="muted">Débat, contradiction, audit logique et analyse littéraire/philosophique.</p></div><div class="cs-tools"><select id="dcThreadSelect" class="cs-thread-select"></select><button id="dcNew" class="ghost small" type="button">+ Nouveau</button><button id="dcMemory" class="ghost small" type="button">Mémoire</button></div></div><div id="dcModes" class="cs-modes"></div><div id="dcThreadView" class="cs-chat"></div><div class="cs-quick"><button data-dcmode="contradiction">⚔ Contredis-moi</button><button data-dcmode="logique">△ Trouve mes erreurs</button><button data-dcmode="litteraire">✦ Analyse mon texte</button><button data-dcmode="socratique">? Pousse-moi</button><button data-dcmode="steelman">◆ Renforce mon idée</button></div><div class="cs-compose"><textarea id="dcInput" autocomplete="off" spellcheck="true" placeholder="Écris ici une idée, une question, un argument ou colle un texte entier…"></textarea><div class="cs-foot"><span>Le clavier doit s’ouvrir dès que tu touches cette zone.</span><button id="dcSend" class="primary" type="button">Envoyer</button></div><div id="dcStatus" class="cs-status"></div></div><div id="dcProfile" class="cs-profile" hidden><div class="label">MÉMOIRE INTELLECTUELLE LOCALE</div><textarea id="dcProfileText" placeholder="Tu peux noter ici la manière dont tu veux être challengé, tes habitudes de raisonnement, concepts récurrents…"></textarea><div style="display:flex;gap:6px;margin-top:6px"><button id="dcProfileSave" class="ghost small" type="button">Enregistrer</button><button id="dcProfileReset" class="ghost small danger" type="button">Réinitialiser</button></div></div>`;const anchor=$('workspacePanel')||$('skillsPanel')||$('resourcesPanel')||$('dashboardPanel');anchor?anchor.insertAdjacentElement('beforebegin',p):(document.querySelector('.app')||document.body).appendChild(p)}
function md(s){if(window.marked){try{return marked.parse(String(s||''))}catch{}}return esc(s).replace(/\n/g,'<br>')}
function setStatus(t=''){if($('dcStatus'))$('dcStatus').textContent=t}
function newChat(){const t={id:uid(),title:'Nouvelle discussion',mode,messages:[],updated:new Date().toISOString()};const a=threads();a.unshift(t);put(a);active=t.id;localStorage.setItem(A,active);render();focus();return t}
function saveThread(t){const a=threads();const i=a.findIndex(x=>x.id===t.id);if(i>=0)a[i]=t;else a.unshift(t);put(a);active=t.id;localStorage.setItem(A,active)}
function setMode(m){if(!modes[m])return;mode=m;const t=current();if(t){t.mode=m;t.updated=new Date().toISOString();saveThread(t)}renderModes();setStatus(modes[m][2])}
function renderModes(){const r=$('dcModes');if(!r)return;r.innerHTML='';Object.entries(modes).forEach(([id,v])=>{const b=document.createElement('button');b.type='button';b.className='cs-mode '+(id===mode?'active':'');b.dataset.dcmode=id;b.textContent=`${v[0]} ${v[1]}`;b.onclick=()=>setMode(id);r.appendChild(b)})}
function renderThreads(){const s=$('dcThreadSelect');if(!s)return;const a=threads();s.innerHTML=a.length?a.map(t=>`<option value="${esc(t.id)}">${esc(t.title||'Discussion')}</option>`).join(''):'<option value="">Nouvelle discussion</option>';if(active&&a.some(t=>t.id===active))s.value=active;s.onchange=()=>{active=s.value;localStorage.setItem(A,active);const t=current();if(t?.mode&&modes[t.mode])mode=t.mode;render()}}
function renderView(){const r=$('dcThreadView');if(!r)return;const t=current();r.innerHTML='';if(!t?.messages?.length){r.innerHTML=`<div class="cs-empty"><b style="display:block;color:#e8ddcb;font:20px Georgia,serif;margin-bottom:5px">${esc(modes[mode][1])}</b>${esc(modes[mode][2])}<br><br>Écris directement dans le champ ci-dessous.</div>`;return}t.messages.forEach(m=>{const d=document.createElement('div');d.className='cs-msg '+(m.role==='user'?'user':'ai');d.innerHTML=`<span class="cs-who">${m.role==='user'?'TOI':'MAJLIS'}</span>${md(m.content)}`;r.appendChild(d)});r.scrollTop=r.scrollHeight}
function render(){const t=current();if(t?.mode&&modes[t.mode])mode=t.mode;renderModes();renderThreads();renderView()}
async function gemini(t){const s=load(S,{});if(!s.apiKey)throw new Error('Ajoute ta clé Gemini dans Réglages.');const model=s.model||'gemini-3.8-flash',memory=load(P,{text:''})?.text||'';const sys=`${prompts[t.mode||mode]}\n\nRéponds en français sauf demande contraire. Sois substantiel, précis et honnête. Distingue fait, interprétation et hypothèse. Ne fabrique pas de source. ${memory?`\n\nMémoire de travail : ${memory}`:''}`;const contents=(t.messages||[]).slice(-20).map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:m.content}]}));const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':s.apiKey},body:JSON.stringify({systemInstruction:{parts:[{text:sys}]},contents,generationConfig:{temperature:.72,topP:.92,maxOutputTokens:3400}})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error?.message||`Gemini ${res.status}`);const txt=(data.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('\n').trim();if(!txt)throw new Error('Aucune réponse reçue.');return txt}
async function send(){if(busy)return;const i=$('dcInput'),text=i?.value.trim();if(!text)return;let t=current()||newChat();t.mode=mode;t.messages=t.messages||[];t.messages.push({role:'user',content:text});if(t.title==='Nouvelle discussion')t.title=text.replace(/\s+/g,' ').slice(0,48);t.updated=new Date().toISOString();saveThread(t);i.value='';render();busy=true;$('dcSend').disabled=true;setStatus('Majlis réfléchit…');try{const rep=await gemini(t);t=current()||t;t.messages.push({role:'assistant',content:rep});t.updated=new Date().toISOString();saveThread(t);render();setStatus('Réponse prête.')}catch(e){setStatus('Erreur : '+e.message)}finally{busy=false;$('dcSend').disabled=false;focus(false)}}
function focus(scroll=true){const i=$('dcInput');if(!i)return false;i.disabled=false;i.readOnly=false;if(scroll)i.scrollIntoView({behavior:'smooth',block:'center'});try{i.focus({preventScroll:true})}catch{i.focus()}return true}
function bind(){$('dcNew').onclick=newChat;$('dcSend').onclick=send;$('dcInput').onfocus=()=>document.body.classList.add('cs-keyboard');$('dcInput').onblur=()=>setTimeout(()=>document.body.classList.remove('cs-keyboard'),120);document.querySelectorAll('#deepChatPanel [data-dcmode]').forEach(b=>b.onclick=()=>setMode(b.dataset.dcmode));$('dcMemory').onclick=()=>{const p=$('dcProfile');p.hidden=!p.hidden;if(!p.hidden)$('dcProfileText').value=load(P,{text:''})?.text||''};$('dcProfileSave').onclick=()=>{save(P,{text:$('dcProfileText').value.trim(),updated:new Date().toISOString()});setStatus('Mémoire enregistrée.')};$('dcProfileReset').onclick=()=>{localStorage.removeItem(P);$('dcProfileText').value='';setStatus('Mémoire réinitialisée.')}}
function open(opts={}){$('deepChatPanel')?.classList.remove('board-space-hidden');if(opts.mode)setMode(opts.mode);setTimeout(()=>focus(opts.focus!==false),80)}
function init(){ui();if(!active||!threads().some(t=>t.id===active)){active=threads()[0]?.id||'';if(active)localStorage.setItem(A,active)}render();bind();window.MajlisDeepChat={open,setMode,focus,newChat,send};window.dispatchEvent(new CustomEvent('majlis:chat-ready'))}
try{init()}catch(e){console.error('Majlis stable chat error',e)}
})();