(()=>{
const $=id=>document.getElementById(id);
const THREADS='majlis.deepchat.threads',ACTIVE='majlis.deepchat.active',PROFILE='majlis.deepchat.profile',SETTINGS='majlis.settings',DRAFT='majlis.draft',PROJECTS='majlis.workspace.projects';
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const MODES={
 libre:{label:'Dialogue libre',icon:'◌',desc:'Partenaire de pensée exigeant, nuancé et interdisciplinaire.',prompt:`Tu es un partenaire intellectuel exigeant. Dialogue réellement avec l'utilisateur : reconstruis son idée avant de la juger, distingue ce qui est solide de ce qui est fragile, apporte des concepts utiles et pousse le raisonnement plus loin. Ne valide pas par politesse. Si une ambiguïté change le fond, signale-la. Réponds de manière substantielle quand la question l'exige.`},
 socratique:{label:'Socratique',icon:'?',desc:'Questions qui forcent à préciser les prémisses et les concepts.',prompt:`Adopte une méthode socratique exigeante. Repère la prémisse décisive, le mot ambigu ou le saut logique. Explique brièvement pourquoi il compte, puis pose une ou deux questions très précises qui obligent l'utilisateur à préciser sa pensée. N'enchaîne pas une liste de questions superficielles.`},
 contradiction:{label:'Contradicteur',icon:'⚔',desc:'Cherche le meilleur contre-argument, pas une objection facile.',prompt:`Sois le contradicteur le plus sérieux possible. Commence par formuler la version la plus forte de l'idée de l'utilisateur, puis attaque-la : prémisses contestables, mécanisme alternatif, contre-exemple, coût caché, donnée qui manquerait, condition où l'idée échoue. Ne caricature jamais. Termine par le test qui pourrait départager les positions.`},
 logique:{label:'Audit logique',icon:'△',desc:'Thèse, prémisses, inférences, biais, erreurs et preuves manquantes.',prompt:`Fais un audit logique rigoureux. Sépare : thèse, prémisses explicites, prémisses cachées, preuves, inférences, ambiguïtés de termes, causalités supposées, contre-exemples possibles et conclusions qui dépassent les prémisses. N'emploie un nom de sophisme que s'il est réellement justifié. Propose ensuite une version plus solide du raisonnement.`},
 litteraire:{label:'Littéraire & philo',icon:'✦',desc:'Lecture stylistique, symbolique et philosophique poussée du texte fourni.',prompt:`Analyse prioritairement le texte fourni par l'utilisateur, sans inventer son intention ni son contexte. Distingue toujours observation textuelle et interprétation. Étudie : voix et position d'énonciation, rythme, syntaxe, lexique, images, métaphores, motifs, répétitions, ruptures, non-dits, tensions, ambiguïtés, architecture du passage et effets produits. Puis mène un prisme philosophique : conception du sujet, du temps, du désir, de la liberté, de la vérité, de la morale, du pouvoir, de l'altérité ou de la mort seulement lorsque le texte les autorise. Donne au moins deux lectures concurrentes quand le passage est polysémique. Identifie les passages les plus forts, les facilités éventuelles et les endroits où une réécriture pourrait intensifier l'effet. Si tu cites, cite seulement des mots réellement fournis par l'utilisateur.`},
 carte:{label:'Carte argumentative',icon:'⌘',desc:'Cartographie la structure profonde d'une idée ou d'un texte.',prompt:`Construis une carte argumentative lisible : question centrale → thèse → prémisses → mécanisme → preuves → hypothèses cachées → objections → réponses possibles → points non résolus. Utilise des flèches Unicode simples et des listes, jamais du LaTeX ni des diagrammes ASCII fragiles.`},
 steelman:{label:'Steelman',icon:'◆',desc:'Reconstruit la meilleure version d'une idée avant de la tester.',prompt:`Fais un steelman. Reconstruis d'abord la version la plus forte, précise et défendable de l'idée de l'utilisateur, y compris les distinctions qu'il aurait intérêt à faire. Indique ensuite ce que cette version gagne par rapport à la formulation initiale. Enfin, soumets cette meilleure version à l'objection la plus difficile.`}
};
let activeId=localStorage.getItem(ACTIVE)||'',mode='libre',busy=false;
function profile(){return Object.assign({text:'',updated:'',seen:0,auto:true},load(PROFILE,{}))}
function threads(){return load(THREADS,[])}
function writeThreads(v){save(THREADS,v.slice(0,24))}
function activeThread(){return threads().find(t=>t.id===activeId)||null}
function markdown(text){
 const safe=esc(String(text||'')).replace(/&quot/g,'&quot;');
 return window.marked?marked.parse(safe):safe.replace(/\n/g,'<br>');
}
function ensureStyle(){
 if($('deepChatStyle'))return;const s=document.createElement('style');s.id='deepChatStyle';s.textContent=`
 .deep-chat{overflow:hidden;border-color:#8b6bc72e;background:linear-gradient(145deg,#171c25,#11161d 68%)}
 .dc-title{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.dc-title h2{font-family:Georgia,serif;color:#f4ead7;font-size:24px;margin:5px 0 4px}.dc-title-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.dc-memory-badge{font-size:9px;color:#bca5e8;border:1px solid #8b6bc750;border-radius:999px;padding:5px 8px;background:#8b6bc70d;white-space:nowrap}
 .dc-modes{display:flex;gap:7px;overflow-x:auto;scrollbar-width:none;padding:12px 0 8px}.dc-modes::-webkit-scrollbar{display:none}.dc-mode{flex:0 0 auto;border:1px solid var(--line);background:#10151c;color:var(--muted);border-radius:999px;padding:7px 10px;font-size:11px}.dc-mode.active{color:#eadfff;border-color:#8b6bc7;background:#8b6bc71a}.dc-mode span{opacity:.8;margin-right:4px}
 .dc-shell{display:grid;grid-template-columns:180px minmax(0,1fr);gap:10px;margin-top:4px}.dc-side{border:1px solid #ffffff0c;border-radius:11px;background:#0f141a;padding:9px;min-width:0}.dc-side-head{display:flex;justify-content:space-between;align-items:center;gap:6px;margin-bottom:7px}.dc-thread-list{display:grid;gap:5px;max-height:480px;overflow:auto}.dc-thread{position:relative;border:1px solid transparent;border-radius:8px;background:#141a22;padding:8px 27px 8px 8px;cursor:pointer;min-width:0}.dc-thread.active{border-color:#8b6bc75c;background:#8b6bc710}.dc-thread b{display:block;color:#ddd7e7;font:12px Georgia,serif;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dc-thread small{color:#6f7886;font-size:8px}.dc-thread-x{position:absolute;right:5px;top:5px;border:0;background:transparent;color:#626b78;padding:2px 4px;font-size:14px}
 .dc-main{min-width:0}.dc-context{display:grid;grid-template-columns:1fr auto;gap:7px;margin-bottom:7px}.dc-context select{font-size:11px}.dc-context-note{font-size:9px;color:#707988;align-self:center}.dc-thread-view{height:min(56vh,560px);min-height:310px;overflow:auto;border:1px solid #ffffff0c;border-radius:12px;background:#0e1319;padding:11px;display:flex;flex-direction:column;gap:9px;scroll-behavior:smooth}.dc-empty{margin:auto;max-width:430px;text-align:center;color:#737d8b;font-size:12px;line-height:1.55}.dc-empty b{display:block;font:20px Georgia,serif;color:#e9dfcf;margin-bottom:6px}
 .dc-msg{max-width:92%;border-radius:12px;padding:11px 12px;line-height:1.58;overflow-wrap:anywhere}.dc-msg.user{align-self:flex-end;background:#242b36;border:1px solid #394250;color:#e8ebf0}.dc-msg.ai{align-self:flex-start;background:linear-gradient(#f0e7d5,#e9dec8);color:#292117;border:1px solid #cabc9d;border-top:3px solid #8b6bc7;font-family:Georgia,serif}.dc-who{display:block;font:8px -apple-system,sans-serif;text-transform:uppercase;letter-spacing:.1em;opacity:.55;margin-bottom:5px}.dc-msg p{margin:.35em 0 .75em}.dc-msg p:last-child{margin-bottom:0}.dc-msg h1,.dc-msg h2,.dc-msg h3{font-family:Georgia,serif;line-height:1.2;margin:1em 0 .4em}.dc-msg h2{font-size:19px}.dc-msg h3{font-size:16px}.dc-msg ul,.dc-msg ol{padding-left:1.25em}.dc-msg blockquote{border-left:3px solid #8b6bc7;padding-left:10px;margin:9px 0;opacity:.88}.dc-msg code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;background:#0000000d;padding:1px 4px;border-radius:4px}
 .dc-quick{display:flex;gap:6px;overflow-x:auto;scrollbar-width:none;padding:8px 0 3px}.dc-quick::-webkit-scrollbar{display:none}.dc-quick button{flex:0 0 auto;font-size:9px;padding:5px 8px;border-radius:999px;border:1px solid #ffffff12;background:#121820;color:#98a1ae}.dc-compose{margin-top:6px;border:1px solid #ffffff10;border-radius:11px;background:#11171e;padding:8px}.dc-compose textarea{margin:0;min-height:105px;max-height:300px;font-size:13px;line-height:1.5}.dc-compose-foot{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:7px}.dc-compose-hint{color:#687281;font-size:9px}.dc-send{min-width:92px}
 .dc-profile{margin-top:10px;border:1px solid #8b6bc730;border-radius:11px;background:#8b6bc708;padding:11px}.dc-profile[hidden]{display:none!important}.dc-profile-head{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.dc-profile h3{font-family:Georgia,serif;color:#eee5f4;margin:3px 0;font-size:17px}.dc-profile textarea{min-height:185px;font-size:11px;line-height:1.55}.dc-profile-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.dc-profile-note{font-size:9px;color:#707988;line-height:1.45;margin-top:6px}.dc-status{font-size:10px;color:#929baa;min-height:16px;margin-top:5px}.dc-status.ok{color:var(--green)}.dc-status.bad{color:var(--red)}
 @media(max-width:650px){.dc-title{display:block}.dc-title-actions{justify-content:flex-start;margin-top:8px}.dc-shell{display:block}.dc-side{margin-bottom:8px}.dc-side-head{margin-bottom:5px}.dc-thread-list{display:flex;overflow-x:auto;max-height:none;gap:6px}.dc-thread{min-width:145px;max-width:190px;flex:0 0 auto}.dc-thread-view{height:52vh;min-height:350px}.dc-context{grid-template-columns:1fr}.dc-context-note{display:none}.dc-msg{max-width:96%;font-size:14px}.dc-compose textarea{font-size:16px}.dc-compose-foot{align-items:flex-end}.dc-compose-hint{max-width:52%}}
 `;document.head.appendChild(s)
}
function ensureUI(){
 if($('deepChatPanel'))return;ensureStyle();const sec=document.createElement('section');sec.id='deepChatPanel';sec.className='panel deep-chat';sec.innerHTML=`
 <div class="dc-title"><div><div class="label">DIALOGUE INTELLECTUEL · MÉMOIRE LOCALE</div><h2>Majlis Socratique</h2><p class="muted">Un espace pour penser à voix haute, être contredit, auditer tes raisonnements et analyser tes textes en profondeur.</p></div><div class="dc-title-actions"><span id="dcMemoryBadge" class="dc-memory-badge">Mémoire intellectuelle</span><button id="dcProfileToggle" class="ghost small" type="button">Voir ma pensée</button><button id="dcNew" class="primary small" type="button">+ Nouveau chat</button></div></div>
 <div id="dcModes" class="dc-modes"></div>
 <div class="dc-shell"><aside class="dc-side"><div class="dc-side-head"><b>Conversations</b><span id="dcCount" class="muted"></span></div><div id="dcThreadList" class="dc-thread-list"></div></aside><div class="dc-main">
  <div class="dc-context"><select id="dcContext"></select><span class="dc-context-note">Le contexte sélectionné est ajouté à la conversation, mais n'est pas publié ailleurs.</span></div>
  <div id="dcThreadView" class="dc-thread-view"></div>
  <div class="dc-quick"><button data-dcmode="contradiction">⚔ Contredis-moi</button><button data-dcmode="logique">△ Trouve mes erreurs</button><button data-dcmode="litteraire">✦ Analyse mon texte</button><button data-dcmode="socratique">? Pousse-moi</button><button data-dcmode="carte">⌘ Carte de mon argument</button><button data-dcmode="steelman">◆ Renforce mon idée</button></div>
  <div class="dc-compose"><textarea id="dcInput" placeholder="Écris une idée, une question, un raisonnement ou colle un texte entier à analyser…"></textarea><div class="dc-compose-foot"><span class="dc-compose-hint">Entrée = envoyer · Maj+Entrée = nouvelle ligne</span><button id="dcSend" class="primary dc-send" type="button">Envoyer</button></div><div id="dcStatus" class="dc-status"></div></div>
 </div></div>
 <div id="dcProfile" class="dc-profile" hidden><div class="dc-profile-head"><div><div class="label">PROFIL INTELLECTUEL DE TRAVAIL</div><h3>Ce que Majlis observe dans ta manière de raisonner</h3></div><label class="muted"><input id="dcProfileAuto" type="checkbox"> auto</label></div><textarea id="dcProfileText" placeholder="Le profil se construit progressivement à partir de tes propres messages."></textarea><div class="dc-profile-actions"><button id="dcProfileUpdate" class="ghost small" type="button">Mettre à jour depuis mes chats</button><button id="dcProfileSave" class="ghost small" type="button">Enregistrer mes corrections</button><button id="dcProfileReset" class="ghost small danger" type="button">Réinitialiser</button></div><div class="dc-profile-note">Ce résumé est stocké uniquement dans le stockage local de Majlis. Il décrit des habitudes de raisonnement observables, pas ta personnalité, ton identité ni des caractéristiques sensibles. Tu peux le corriger à tout moment.</div></div>`;
 const anchor=$('skillsPanel')||$('workspacePanel')||$('resourcesPanel');if(anchor)anchor.insertAdjacentElement('beforebegin',sec);else document.querySelector('.app')?.appendChild(sec)
}
function renderModes(){const root=$('dcModes');root.innerHTML='';Object.entries(MODES).forEach(([id,m])=>{const b=document.createElement('button');b.type='button';b.className='dc-mode '+(mode===id?'active':'');b.innerHTML=`<span>${m.icon}</span>${m.label}`;b.title=m.desc;b.onclick=()=>{mode=id;const t=activeThread();if(t){const all=threads(),x=all.find(v=>v.id===t.id);if(x){x.mode=id;x.updated=new Date().toISOString();writeThreads(all)}}renderModes();renderThreadList();setStatus(m.desc)};root.appendChild(b)})}
function newThread(prefill=''){const all=threads();const t={id:uid(),title:'Nouvelle réflexion',mode,context:'none',messages:[],created:new Date().toISOString(),updated:new Date().toISOString()};all.unshift(t);writeThreads(all);activeId=t.id;localStorage.setItem(ACTIVE,activeId);renderAll();if(prefill)$('dcInput').value=prefill;setTimeout(()=>$('dcInput')?.focus(),50);return t}
function deleteThread(id){let all=threads().filter(t=>t.id!==id);writeThreads(all);if(activeId===id){activeId=all[0]?.id||'';if(activeId)localStorage.setItem(ACTIVE,activeId);else localStorage.removeItem(ACTIVE)}renderAll()}
function selectThread(id){activeId=id;localStorage.setItem(ACTIVE,id);const t=activeThread();if(t)mode=t.mode||'libre';renderAll()}
function renderThreadList(){const root=$('dcThreadList'),all=threads();$('dcCount').textContent=all.length?String(all.length):'';root.innerHTML='';if(!all.length){root.innerHTML='<span class="muted">Aucun chat.</span>';return}all.sort((a,b)=>new Date(b.updated)-new Date(a.updated)).forEach(t=>{const d=document.createElement('div');d.className='dc-thread '+(t.id===activeId?'active':'');d.innerHTML=`<b>${esc(t.title||'Réflexion')}</b><small>${esc(MODES[t.mode]?.label||'Dialogue')} · ${new Date(t.updated).toLocaleDateString('fr-FR')}</small><button class="dc-thread-x" type="button" aria-label="Supprimer">×</button>`;d.onclick=e=>{if(!e.target.closest('.dc-thread-x'))selectThread(t.id)};d.querySelector('.dc-thread-x').onclick=e=>{e.stopPropagation();deleteThread(t.id)};root.appendChild(d)})}
function populateContext(){const sel=$('dcContext');if(!sel)return;const t=activeThread();const previous=t?.context||'none';sel.innerHTML='<option value="none">Aucun contexte externe</option><option value="course">Cours actuel Majlis</option>';const ps=load(PROJECTS,[]);if(ps.length){const group=document.createElement('optgroup');group.label='Mes projets';ps.slice(0,20).forEach(p=>{const o=document.createElement('option');o.value=`project:${p.id}`;o.textContent=p.name||'Projet';group.appendChild(o)});sel.appendChild(group)};if([...sel.options].some(o=>o.value===previous))sel.value=previous;else sel.value='none';sel.onchange=()=>{const all=threads(),x=all.find(v=>v.id===activeId);if(x){x.context=sel.value;x.updated=new Date().toISOString();writeThreads(all)}}}
function renderConversation(){const root=$('dcThreadView'),t=activeThread();root.innerHTML='';if(!t||!t.messages?.length){root.innerHTML='<div class="dc-empty"><b>Un espace pour éprouver ta pensée.</b>Écris une intuition, colle un texte, défends une thèse ou choisis un mode. Majlis cherchera la structure profonde de ce que tu dis plutôt qu’une réponse polie.</div>';return}(t.messages||[]).forEach(m=>{const d=document.createElement('div');d.className='dc-msg '+(m.role==='user'?'user':'ai');d.innerHTML=`<span class="dc-who">${m.role==='user'?'Toi':`Majlis · ${esc(MODES[m.mode]?.label||'Dialogue')}`}</span>${markdown(m.content)}`;root.appendChild(d)});root.scrollTop=root.scrollHeight}
function renderProfile(){const p=profile();$('dcProfileText').value=p.text||'';$('dcProfileAuto').checked=p.auto!==false;$('dcMemoryBadge').textContent=p.updated?`Mémoire · ${new Date(p.updated).toLocaleDateString('fr-FR')}`:'Mémoire intellectuelle'}
function renderAll(){const t=activeThread();if(t)mode=t.mode||'libre';renderModes();renderThreadList();populateContext();renderConversation();renderProfile()}
function setStatus(text='',kind=''){const e=$('dcStatus');if(!e)return;e.textContent=text;e.className='dc-status '+kind}
function contextBlock(value){if(!value||value==='none')return'';if(value==='course'){const d=load(DRAFT,null);if(!d?.content)return'CONTEXTE SÉLECTIONNÉ : aucun cours actuel disponible.';return`CONTEXTE — COURS ACTUEL\nSujet: ${d.topic||''}\n\n${String(d.content).slice(0,14000)}`};if(value.startsWith('project:')){const id=value.slice(8),p=load(PROJECTS,[]).find(x=>x.id===id);if(!p)return'';const tasks=(p.tasks||[]).map(t=>`- [${t.done?'x':' '}] ${t.text}`).join('\n');return`CONTEXTE — PROJET\nNom: ${p.name||''}\nObjectif: ${p.goal||''}\nNotes:\n${String(p.notes||'').slice(0,9000)}\nTâches:\n${tasks}`};return''}
function packMessages(t){const src=t.messages||[],out=[];let total=0;for(let i=src.length-1;i>=0;i--){const m=src[i],len=String(m.content||'').length;if(total+len>36000&&out.length>5)break;out.unshift({role:m.role,content:String(m.content||'').slice(0,12000)});total+=len}return out}
async function gemini(system,messages,maxTokens=3200){const s=load(SETTINGS,{});if(!s.apiKey){$('settingsBtn')?.click();throw new Error('Ajoute ta clé Gemini dans Réglages.')}const model=s.model||'gemini-3.8-flash';const contents=messages.map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:m.content}]}));const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':s.apiKey},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents,generationConfig:{temperature:.66,topP:.92,maxOutputTokens:maxTokens}})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error?.message||`Gemini ${r.status}`);const text=(data.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('\n').trim();if(!text)throw new Error('Aucune réponse reçue.');return text}
function systemPrompt(t){const p=profile();const intellectual=p.text?`\n\nMÉMOIRE INTELLECTUELLE DE TRAVAIL — hypothèses révisables, pas des faits sur la personne:\n${p.text}\nUtilise-la seulement pour mieux choisir le niveau de contradiction, les distinctions et les questions. Si la conversation actuelle la contredit, privilégie la conversation actuelle.`:'';const ctx=contextBlock(t.context);return`Tu es Majlis dans son laboratoire de dialogue intellectuel. Réponds en français sauf demande contraire. Tu dois aider l'utilisateur à penser plus précisément, pas simplement être agréable. Distingue observation, interprétation, inférence et spéculation. Ne suppose jamais ses intentions. N'infère pas d'attributs sensibles, de diagnostic psychologique, d'identité politique ou religieuse. Pour les textes fournis, reste ancré dans le texte et signale clairement toute interprétation. N'utilise pas de LaTeX brut ni de schéma ASCII fragile.\n\nMODE ACTUEL — ${MODES[t.mode||mode].label}:\n${MODES[t.mode||mode].prompt}${intellectual}${ctx?`\n\n${ctx}`:''}`}
function appendMessage(threadId,role,content,msgMode=mode){const all=threads(),t=all.find(x=>x.id===threadId);if(!t)return;t.messages=t.messages||[];t.messages.push({id:uid(),role,content,mode:msgMode,date:new Date().toISOString()});t.messages=t.messages.slice(-80);if(role==='user'&&t.messages.filter(x=>x.role==='user').length===1)t.title=String(content).replace(/\s+/g,' ').slice(0,58)||'Réflexion';t.updated=new Date().toISOString();writeThreads(all)}
async function send(){const input=$('dcInput'),text=input.value.trim();if(!text||busy)return;let t=activeThread();if(!t)t=newThread();const id=t.id;appendMessage(id,'user',text,t.mode||mode);input.value='';renderThreadList();renderConversation();busy=true;$('dcSend').disabled=true;setStatus('Majlis examine le raisonnement…');try{t=threads().find(x=>x.id===id);const reply=await gemini(systemPrompt(t),packMessages(t),t.mode==='socratique'?1800:t.mode==='litteraire'?4200:3200);appendMessage(id,'assistant',reply,t.mode||mode);renderConversation();renderThreadList();setStatus('Réponse prête.','ok');maybeAutoProfile()}catch(e){setStatus(`Erreur : ${e.message}`,'bad')}finally{busy=false;$('dcSend').disabled=false}}
function userCorpus(){const all=threads(),parts=[];all.sort((a,b)=>new Date(b.updated)-new Date(a.updated)).forEach(t=>(t.messages||[]).filter(m=>m.role==='user').slice(-15).forEach(m=>parts.push(`[${t.title}] ${m.content}`)));return parts.slice(-60).join('\n\n---\n\n').slice(-42000)}
async function updateProfile(manual=true){const corpus=userCorpus();if(corpus.length<180){if(manual)setStatus('Il faut encore quelques messages pour construire un profil utile.');return}const btn=$('dcProfileUpdate');if(btn)btn.disabled=true;setStatus('Majlis synthétise tes habitudes de raisonnement…');try{const old=profile().text||'';const prompt=`Voici uniquement des messages écrits par l'utilisateur dans son laboratoire intellectuel. Construis un profil de TRAVAIL centré exclusivement sur ses habitudes intellectuelles observables. Ne diagnostique rien. N'infère ni identité, ni santé mentale, ni religion, ni orientation politique, ni autres attributs sensibles. Reste prudent: écris "semble" ou "à vérifier" lorsque nécessaire.\n\nProfil précédent éventuel:\n${old||'Aucun'}\n\nMessages utilisateur:\n${corpus}\n\nFormat obligatoire:\n### Questions récurrentes\n### Manière de raisonner observée\n### Forces intellectuelles observables\n### Points à éprouver / angles morts possibles\n### Concepts et tensions récurrentes\n### Comment me challenger efficacement\n### Format de réponse qui semble le plus utile\n\nSois précis, compact et révisable. N'utilise que ce que les messages soutiennent.`;const text=await gemini('Tu es un analyste méthodologique prudent. Tu décris des habitudes de raisonnement à partir de textes, sans psychologie sauvage ni inférence sensible.',[{role:'user',content:prompt}],1600);const p=profile();p.text=text;p.updated=new Date().toISOString();p.seen=threads().reduce((n,t)=>n+(t.messages||[]).filter(m=>m.role==='user').length,0);save(PROFILE,p);renderProfile();setStatus('Mémoire intellectuelle mise à jour.','ok')}catch(e){if(manual)setStatus(`Mémoire : ${e.message}`,'bad')}finally{if(btn)btn.disabled=false}}
function maybeAutoProfile(){const p=profile();if(p.auto===false)return;const count=threads().reduce((n,t)=>n+(t.messages||[]).filter(m=>m.role==='user').length,0);if(count-(p.seen||0)>=6)updateProfile(false)}
function saveProfileEdits(){const p=profile();p.text=$('dcProfileText').value.trim();p.updated=new Date().toISOString();p.auto=$('dcProfileAuto').checked;save(PROFILE,p);renderProfile();setStatus('Profil corrigé et enregistré.','ok')}
function resetProfile(){if(!confirm('Réinitialiser la mémoire intellectuelle du chat ?'))return;localStorage.removeItem(PROFILE);renderProfile();setStatus('Mémoire intellectuelle réinitialisée.')}
function bind(){
 $('dcNew').onclick=()=>newThread();$('dcSend').onclick=send;$('dcInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};
 document.querySelectorAll('[data-dcmode]').forEach(b=>b.onclick=()=>{mode=b.dataset.dcmode;const t=activeThread();if(t){const all=threads(),x=all.find(v=>v.id===t.id);if(x){x.mode=mode;writeThreads(all)}}renderModes();renderThreadList();$('dcInput').focus();setStatus(MODES[mode].desc)});
 $('dcProfileToggle').onclick=()=>{$('dcProfile').hidden=!$('dcProfile').hidden;if(!$('dcProfile').hidden)renderProfile()};$('dcProfileUpdate').onclick=()=>updateProfile(true);$('dcProfileSave').onclick=saveProfileEdits;$('dcProfileReset').onclick=resetProfile;$('dcProfileAuto').onchange=saveProfileEdits;
}
function init(){ensureUI();let all=threads();if(!all.length)newThread();else if(!activeThread()){activeId=all[0].id;localStorage.setItem(ACTIVE,activeId)}bind();renderAll()}
window.MajlisDeepChat={newThread,updateProfile};
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();