(()=>{
const $=id=>document.getElementById(id);
const PKEY='majlis.workspace.projects';
const IKEY='majlis.workspace.inbox';
const SKEY='majlis.settings';
let activeId=null;
let statusFilter='all';
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function projects(){return load(PKEY,[])}
function writeProjects(v){save(PKEY,v)}
function inbox(){return load(IKEY,[])}
function writeInbox(v){save(IKEY,v)}
function touch(p){p.updated=new Date().toISOString()}
function findProject(id=activeId){return projects().find(p=>p.id===id)}
function projectStatusLabel(s){return({idea:'Idée',active:'Actif',paused:'Pause',done:'Terminé'})[s]||'Actif'}
function setWorkspaceStatus(t,ok=true){const e=$('workspaceStatus');if(!e)return;e.textContent=t;e.className='workspace-status '+(ok?'ok':'bad');if(t)setTimeout(()=>{if(e.textContent===t)e.textContent=''},2500)}
function renderStatusFilters(){const wrap=$('projectFilters');if(!wrap)return;const defs=[['all','Tous'],['active','Actifs'],['idea','Idées'],['paused','Pause'],['done','Terminés']];wrap.innerHTML='';defs.forEach(([id,label])=>{const b=document.createElement('button');b.type='button';b.className='project-chip '+(statusFilter===id?'active':'');b.textContent=label;b.onclick=()=>{statusFilter=id;renderStatusFilters();renderProjects()};wrap.appendChild(b)})}
function renderProjects(){const wrap=$('projectList');if(!wrap)return;const all=projects();const list=all.filter(p=>statusFilter==='all'||p.status===statusFilter).sort((a,b)=>new Date(b.updated)-new Date(a.updated));$('projectCount').textContent=`${all.length} projet${all.length>1?'s':''}`;wrap.innerHTML='';if(!list.length){wrap.innerHTML='<div class="workspace-empty">Aucun projet ici. Crée-en un ou transforme ton sujet actuel en projet.</div>';return}list.forEach(p=>{const tasks=p.tasks||[];const done=tasks.filter(t=>t.done).length;const card=document.createElement('button');card.type='button';card.className='project-card '+(p.id===activeId?'selected':'');card.innerHTML=`<span class="project-card-top"><b>${esc(p.name)}</b><span class="project-status ${esc(p.status)}">${esc(projectStatusLabel(p.status))}</span></span><span class="project-goal-mini">${esc(p.goal||'Objectif à préciser')}</span><span class="project-meta">${tasks.length?`${done}/${tasks.length} tâches`:'Aucune tâche'} · ${new Date(p.updated).toLocaleDateString('fr-FR')}</span>`;card.onclick=()=>openProject(p.id);wrap.appendChild(card)})}
function createProject(name,status='active',goal=''){name=(name||'').trim();if(!name)return null;const all=projects();const p={id:uid(),name,goal,status,notes:'',tasks:[],chat:[],created:new Date().toISOString(),updated:new Date().toISOString()};all.unshift(p);writeProjects(all);activeId=p.id;renderProjects();openProject(p.id);return p}
function deleteProject(){const p=findProject();if(!p)return;if(!confirm(`Supprimer le projet « ${p.name} » ?`))return;writeProjects(projects().filter(x=>x.id!==p.id));activeId=null;$('projectEditor').hidden=true;renderProjects();setWorkspaceStatus('Projet supprimé.')}
function openProject(id){activeId=id;const p=findProject(id);if(!p)return;renderProjects();$('projectEditor').hidden=false;$('projectName').value=p.name||'';$('projectGoal').value=p.goal||'';$('projectNotes').value=p.notes||'';$('projectStatus').value=p.status||'active';$('projectTitle').textContent=p.name||'Projet';renderTasks();renderChat();setTimeout(()=>$('projectEditor').scrollIntoView({behavior:'smooth',block:'start'}),50)}
function persistEditor(){const all=projects();const p=all.find(x=>x.id===activeId);if(!p)return;p.name=$('projectName').value.trim()||p.name;p.goal=$('projectGoal').value.trim();p.notes=$('projectNotes').value;p.status=$('projectStatus').value;touch(p);writeProjects(all);$('projectTitle').textContent=p.name;renderProjects();setWorkspaceStatus('Enregistré ✓')}
let saveTimer=null;
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(persistEditor,450)}
function addTask(){const text=$('taskInput').value.trim();if(!text)return;const all=projects(),p=all.find(x=>x.id===activeId);if(!p)return;p.tasks=p.tasks||[];p.tasks.push({id:uid(),text,done:false});touch(p);writeProjects(all);$('taskInput').value='';renderTasks();renderProjects()}
function toggleTask(id){const all=projects(),p=all.find(x=>x.id===activeId);if(!p)return;const t=(p.tasks||[]).find(x=>x.id===id);if(t)t.done=!t.done;touch(p);writeProjects(all);renderTasks();renderProjects()}
function removeTask(id){const all=projects(),p=all.find(x=>x.id===activeId);if(!p)return;p.tasks=(p.tasks||[]).filter(x=>x.id!==id);touch(p);writeProjects(all);renderTasks();renderProjects()}
function renderTasks(){const p=findProject();const wrap=$('taskList');if(!p||!wrap)return;wrap.innerHTML='';const list=p.tasks||[];if(!list.length){wrap.innerHTML='<span class="muted">Aucune tâche. Ajoute la prochaine action concrète.</span>';return}list.forEach(t=>{const row=document.createElement('div');row.className='task-row '+(t.done?'done':'');row.innerHTML=`<button class="task-check" type="button" aria-label="Terminer">${t.done?'✓':'○'}</button><span>${esc(t.text)}</span><button class="task-remove" type="button" aria-label="Supprimer">×</button>`;row.querySelector('.task-check').onclick=()=>toggleTask(t.id);row.querySelector('.task-remove').onclick=()=>removeTask(t.id);wrap.appendChild(row)})}
function renderInbox(){const wrap=$('inboxList');if(!wrap)return;const list=inbox().sort((a,b)=>b.ts-a.ts);$('inboxCount').textContent=list.length?`${list.length} capture${list.length>1?'s':''}`:'';wrap.innerHTML='';if(!list.length){wrap.innerHTML='<span class="muted">Tes idées rapides apparaîtront ici.</span>';return}list.slice(0,8).forEach(item=>{const row=document.createElement('div');row.className='inbox-item';row.innerHTML=`<div><b>${esc(item.text)}</b><small>${new Date(item.ts).toLocaleString('fr-FR',{dateStyle:'short',timeStyle:'short'})}</small></div><div class="inbox-actions"><button type="button" class="ghost small">→ Projet</button><button type="button" class="ghost small">×</button></div>`;const [toProject,del]=row.querySelectorAll('button');toProject.onclick=()=>{createProject(item.text,'idea','');writeInbox(inbox().filter(x=>x.id!==item.id));renderInbox()};del.onclick=()=>{writeInbox(inbox().filter(x=>x.id!==item.id));renderInbox()};wrap.appendChild(row)})}
function captureInbox(){const input=$('quickCapture');const text=input.value.trim();if(!text)return;const list=inbox();list.unshift({id:uid(),text,ts:Date.now()});writeInbox(list.slice(0,60));input.value='';renderInbox();setWorkspaceStatus('Idée capturée ✓')}
function fromCurrentTopic(){const topic=$('topic')?.value?.trim();if(!topic){setWorkspaceStatus('Écris d’abord un sujet dans Majlis.',false);return}const p=createProject(topic,'active','Transformer ce sujet en projet concret et avancer étape par étape.');if(p){const current=load('majlis.draft',null);if(current?.content){const all=projects(),x=all.find(v=>v.id===p.id);if(x){x.notes=`Contexte importé depuis une session Majlis :\n\n${String(current.content).slice(0,7000)}`;touch(x);writeProjects(all);openProject(x.id)}}}}
async function callGemini(prompt){const settings=load(SKEY,{});if(!settings.apiKey){$('settingsBtn')?.click();throw new Error('Ajoute ta clé Gemini dans Réglages.')}const model=settings.model||'gemini-3.8-flash';const res=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':settings.apiKey},body:JSON.stringify({systemInstruction:{parts:[{text:'Tu es le copilote de projet de Majlis. Sois exigeant, concret, structuré, critique et orienté action. Tu aides à clarifier, décider, planifier, écrire, questionner les hypothèses et transformer les idées en résultats. Réponds en français sauf demande contraire.'}]},contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:.62,topP:.9,maxOutputTokens:2200}})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data?.error?.message||`Gemini ${res.status}`);const text=(data.candidates?.[0]?.content?.parts||[]).map(x=>x.text||'').join('\n').trim();if(!text)throw new Error('Aucune réponse reçue.');return text}
function projectContext(p){const tasks=(p.tasks||[]).map(t=>`- [${t.done?'x':' '}] ${t.text}`).join('\n')||'Aucune';return `PROJET: ${p.name}\nSTATUT: ${projectStatusLabel(p.status)}\nOBJECTIF: ${p.goal||'Non défini'}\nNOTES:\n${p.notes||'Aucune'}\nTÂCHES:\n${tasks}`}
async function aiAction(kind){const p=findProject();if(!p)return;const defs={clarify:'Clarifie ce projet. Reformule le vrai objectif, identifie le résultat mesurable, les hypothèses implicites, ce qui est flou et ce qui doit être décidé maintenant.',next:'Donne les 5 prochaines actions les plus utiles, ordonnées, concrètes et petites. Distingue ce qui prend moins de 30 minutes de ce qui demande un bloc de travail.',plan:'Construis un plan réaliste sur 7 jours, avec une priorité par jour, critères de réussite et risque principal.',challenge:'Joue le rôle du contradicteur. Cherche les failles, coûts cachés, dépendances, biais, scénarios d’échec et propose une version plus robuste du projet.',write:'À partir du projet, propose une note de cadrage claire et professionnelle: problème, objectif, utilisateurs, proposition de valeur, périmètre, étapes, risques et métriques.'};const instruction=defs[kind];if(!instruction)return;const button=document.querySelector(`[data-ai="${kind}"]`);if(button)button.disabled=true;setWorkspaceStatus('Majlis analyse le projet…');try{const text=await callGemini(`${projectContext(p)}\n\nINSTRUCTION:\n${instruction}`);appendChat('assistant',text,kind);renderChat();setWorkspaceStatus('Analyse ajoutée ✓')}catch(e){setWorkspaceStatus(`Erreur : ${e.message}`,false)}finally{if(button)button.disabled=false}}
function appendChat(role,content,tag=''){const all=projects(),p=all.find(x=>x.id===activeId);if(!p)return;p.chat=p.chat||[];p.chat.push({id:uid(),role,content,tag,date:new Date().toISOString()});p.chat=p.chat.slice(-40);touch(p);writeProjects(all);renderProjects()}
async function askProject(){const q=$('projectQuestion').value.trim();const p=findProject();if(!q||!p)return;$('askProject').disabled=true;appendChat('user',q);$('projectQuestion').value='';renderChat();setWorkspaceStatus('Majlis réfléchit…');try{const recent=(p.chat||[]).slice(-8).map(m=>`${m.role==='user'?'Moi':'Majlis'}: ${m.content}`).join('\n\n');const text=await callGemini(`${projectContext(findProject())}\n\nCONVERSATION RÉCENTE:\n${recent}\n\nQUESTION ACTUELLE:\n${q}\n\nRéponds en tenant compte du projet, puis termine si utile par une prochaine action concrète.`);appendChat('assistant',text,'question');renderChat();setWorkspaceStatus('Réponse ajoutée ✓')}catch(e){setWorkspaceStatus(`Erreur : ${e.message}`,false)}finally{$('askProject').disabled=false}}
function renderChat(){const p=findProject();const wrap=$('projectChat');if(!p||!wrap)return;const list=p.chat||[];wrap.innerHTML='';if(!list.length){wrap.innerHTML='<div class="workspace-empty">Pose une question sur ce projet ou utilise un bouton IA. Majlis conservera le fil.</div>';return}list.slice(-12).forEach(m=>{const d=document.createElement('div');d.className='project-msg '+(m.role==='user'?'me':'ai');const html=window.marked?marked.parse(m.content):esc(m.content).replace(/\n/g,'<br>');d.innerHTML=`<span class="project-msg-who">${m.role==='user'?'Toi':'Majlis'}</span>${html}`;wrap.appendChild(d)});wrap.scrollTop=wrap.scrollHeight}
function bind(){
$('createProject').onclick=()=>{const p=createProject($('newProjectName').value);if(p)$('newProjectName').value=''};
$('newProjectName').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('createProject').click()}};
$('projectFromTopic').onclick=fromCurrentTopic;
$('captureBtn').onclick=captureInbox;
$('quickCapture').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();captureInbox()}};
['projectName','projectGoal','projectNotes','projectStatus'].forEach(id=>$(id).addEventListener(id==='projectStatus'?'change':'input',scheduleSave));
$('taskAdd').onclick=addTask;$('taskInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addTask()}};
$('deleteProject').onclick=deleteProject;
document.querySelectorAll('[data-ai]').forEach(b=>b.onclick=()=>aiAction(b.dataset.ai));
$('askProject').onclick=askProject;$('projectQuestion').onkeydown=e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();askProject()}};
}
function init(){renderStatusFilters();renderProjects();renderInbox();bind();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
